version: '3.1'

services:

  letsencrypt-nginx-container:
    container_name: 'letsencrypt-nginx-container'
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - /lets-encrypt-docker-nginx/conf:/etc/nginx/conf.d
      - /lets-encrypt-docker-nginx/letsencrypt-site:/usr/share/nginx/html